version: "3.8"
   
services:

  athena:
    build: .
    container_name: athena
    hostname: athena
    volumes:
      - .:/app
    ports:
      - "9001:9001"
  resources:
    limits:
      cpus: 1
      memory: 500M
