name: build

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start services
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker compose.yml"

    - name: Start services
      run: |
        docker compose up -d --build

    - name: List services
      run: |
        docker compose ps

    - name: Cargo clippy
      run: |
        docker compose exec athena cargo clippy

    - name: Cargo fmt
      run: |
        docker compose exec athena cargo fmt --all -- --check
