name: build

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start services
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"

    - name: Start services
      run: |
        docker-compose up -d --build

    - name: List services
      run: |
        docker-compose ps

    - name: Cargo check
      run: |
        docker-compose exec athena cargo check

    - name: Cargo fmt
      run: |
        docker-compose exec athena cargo fmt --all -- --check

    - name: Cargo fmt
      run: |
        docker-compose exec athena cargo clippy